apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: inbox-receivemsg-process
data:
  application.yml: |+
    spring:
      application:
        name: inbox-receivemsg-process
      r2dbc:
          url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password: password
          port: 9000
      redis:
        host: localhost
        port: 6379
      cloud:
        stream:
          binders:
            batchKafka:
              type: kafka
              environment:
                spring.cloud.stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
                      zkNodes: localhost:2181
                      autoCreateTopics: true
    redis-config:
      expire-times:
        register-cif-Id: 5s