apiVersion: v1
kind: Service
metadata:
  namespace: paotang-v2
  labels:
    app: ekyc-registration-api-service
  name: ekyc-registration-api-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: ekyc-registration-api
  selector:
    app: ekyc-registration-api-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: paotang-v2
  name: ekyc-registration-api-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekyc-registration-api-pod
  template:
    metadata:
      labels:
        app: ekyc-registration-api-pod
    spec:
      volumes:
        - name: volume-configmap
          configMap:
            name: config-ekyc-registration-api
        - name: volume-pvc
          persistentVolumeClaim:
            claimName: paotang-pvc-v2
      containers:
        - name: ekyc-registration-api
          image: ktbirp81.ktb:5000/paotang/v2/ekyc-registration-api:uat
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx256m -Djava.security.egd=file:/dev/./urandom"
            - name: TIME_ZONE
              value: "-Dlogback.timezone=Asia/Bangkok"
            - name: DB_QRCMBU_USERNAME
              valueFrom:
                secretKeyRef:
                  name: paotang-secret
                  key: db.qrcmbu.username
            - name: DB_QRCMBU_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paotang-secret
                  key: db.qrcmbu.password
          volumeMounts:
            - name: volume-configmap
              mountPath: /home
            - name: volume-pvc
              mountPath: /data
          imagePullPolicy: Always
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      securityContext: {}
      terminationGracePeriodSeconds: 30