spring.cloud.stream:
  kafka:
    binder:
      autoCreateTopics: false
      consumerProperties:
        isolation.level: read_committed
    bindings:
      InboxReceiveMessageConsume:
        consumer:
          autoCommitOffset: true
          autoCommitOnError: false
          configuration:
            max.poll.records: 1
            max.poll.interval.ms: 60000
      InboxReceiveMessageProduce:
        producer:
          configuration:
            acks: all
            delivery.timeout.ms: 15000
            max.block.ms: 15000
            request.timeout.ms: 15000
            retry.backoff.ms: 250
            retries: 20
  bindings:
    InboxReceiveMessageConsume:
      destination: test
      group: ekyc.registration.process
      binder: batchKafka
    InboxReceiveMessageProduce:
      destination: test
      group: ekyc.registration.process
      binder: batchKafka