server:
  port: 8888
spring:
  application:
    name: inbox-receivemsg-process
  profiles:
    active: dev
    include:
      - settings
      - discovery
      - stream
---
spring:
  profiles: dev
#  r2dbc:
#    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: password
#    port: 9000
  r2dbc:
    url: r2dbc:mssql://localhost:1433/QRCMBU
    username: sa
    password: P@ssw0rd
    time-out: 10s
    pool:
      initial-size: 4
      max-size: 4
      max-idle-time: 1m
      validation-query: "SELECT 1"
  redis:
    host: localhost
    port: 6379
  cloud:
    stream:
      binders:
        batchKafka:
          type: kafka
          environment:
            spring.cloud.stream:
              kafka:
                binder:
                  brokers: localhost:9092
                  zkNodes: localhost:2181
                  autoCreateTopics: true

logging.level.org.springframework.data.r2dbc: DEBUG
---

